// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvpryntlkuonjehpwldy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cHJ5bnRsa3VvbmplaHB3bGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDI5NzcsImV4cCI6MjA3MTUxODk3N30.RAA2UvFVTVfhVnN5bvGQeapprsPYITqMOhwAWrvPWl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});